version: '3'

services:
  project-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./php:/app
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - project-php-fpm
      - project-php-cli
    environment:
      PROJECT_HOST_NAME: "localhost"
      PROJECT_HOST_PORT: 80
    ports:
      - "80:80"

  project-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./php:/app

  project-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./php:/app
    tty: true

volumes:
  composer:
